config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :static_images
  end
end

app/models/spree/static_image.rb
class Spree::StaticImage < Spree::Image
end

app/controllers/spree/admin/static_images_controller.rb
class Spree::Admin::StaticImagesController < Spree::Admin::ResourceController

  def index
    @static = params[:static] == 'static'

    if @static
      @images = Spree::StaticImage.all
    else
      @images = Spree::Image.where('viewable_id is not null').order('viewable_id').includes(:viewable).all
    end

  end

  def create
    filenames = Array(params[:filenames])
    filenames.each do |filename|
      Spree::StaticImage.create(attachment: filename)
    end

    if filenames.present?
      flash[:success] = "Added #{filenames.length} images"
    end

    redirect_to admin_static_images_path(static: :static)
  end

  def new
    @static_image = Spree::StaticImage.new
  end

end

app/views/spree/admin/static_images/index.html.erb
<%= stylesheet_link_tag 'admin/spree_static_images.css' %>
<%= javascript_include_tag 'admin/spree_static_images.js' %>

<% image_options = @images.first.attachment.styles.map{|k,v| ["#{k} (#{v.geometry.gsub(/[>\^#]$/,' px')})", k]}.push([:original, :original]) %>
<% image_sizes = image_options.map{|o| o.last} %>

<% content_for :page_title do %>
  <%= @images.length %> Static Images
<% end %>

<div class='image-top'>
  <div class='new-image-button'>
    <%= button_to "Add Images", new_admin_static_image_path, {method: :get} %>
  </div>

  <span class='static-radio'>
    <%= radio_button_tag(:static, :product, !@static) %>
    <%= label_tag(:static_product, 'Show Images From Products / Variants') %>
  </span>

  <span class='static-radio'>
    <%= radio_button_tag(:static, :static, @static) %>
    <%= label_tag(:static_static, 'Show Other Images') %>
  </span>
</div>

<table id='static-images'>
  <tr>
    <th>Product</th>
    <th>
      Choose Size
      <br>
      <%= select_tag 'size', options_for_select(image_options), id: 'setAllSizes' %>
    </th>
    <th>Image</th>
    <th>HTML</th>
  </tr>
  <% @images.each do |image| %>
    <tr class='image-row'>
      <td>
        <% if image.viewable %>
          <%= link_to image.viewable.name, product_path(image.viewable.permalink) %>
          <br>
          <br>
          <%= button_to 'Manage Images', admin_product_images_path(image.viewable.permalink), { method: :get } %>
          <%= button_to 'Edit Product', edit_admin_product_path(image.viewable.permalink), { method: :get }  %>
        <% else %>
            Filename: <%= image.attachment_file_name %>
            (not tied to any product)
            <br></br>
            <%= link_to 'Delete', admin_static_image_path(image), method: :delete, data: { confirm: 'Are you sure you want to delete this image?' } %>
        <% end %>
      </td>
      <td class='sizes'>
        <%= select_tag 'size', options_for_select(image_options) %>
      </td>
      <td>
        <% image_sizes.each do |size| %>
          <%= image_tag(image.attachment.url(size), class: "size #{size}") %>
        <% end %>
      </td>
      <td>
        <% image_sizes.each do |size| %>
          <div class='size <%= size %>'>
            <div class='copy' data-html='<%= "#{image.attachment.url(size)}" %>'>
              Copy URL to clipboard
            </div>
            <div class='copy' data-html='<%= "#{image_tag(image.attachment.url(size))}" %>'>
              Copy HTML image tag to clipboard
            </div>
          </div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/static_images/new.html.erb
<%= stylesheet_link_tag 'admin/spree_static_images.css' %>
<%= javascript_include_tag 'admin/spree_static_images.js' %>

<% content_for :page_title do %>
  Static Images
<% end %>

Drag-and-drop the images you want to add, then click 'ADD IMAGES'

<%= form_for [:admin, @static_image], html: { multipart: true} do |f| %>
  <%= file_field_tag 'filenames[]', type: :file, multiple: true %>
  <%= f.submit 'Add Images' %>
<% end %>